runtime: python310

entrypoint: python ODH_Bot.py

env_variables:
  BOT_TOKEN: "MTA4NTg1MTMxODg1NTQwMTUyMg.GMcxx-.0ZVqtH91bRHJ17LuSqcxkK8RUwfT94xsb1zb44"
  Bot_Name: "Echo"
  OPENAI_API_KEY: "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"
